[versions]
kotlin = "2.4.0"
javafx = "21.0.8"
coroutines = "1.11.0"
okhttp = "4.12.0"
jsoup = "1.17.2"
gson = "2.11.0"
jackson = "2.17.2"
nicehttp = "0.4.18"
rhino = "1.8.1"
ktor = "3.5.0"
ksoup = "0.2.6"
datetime = "0.8.0"
atomicfu = "0.33.0"
newpipeextractor = "v0.26.3"
cryptography = "0.6.0"
serializationJson = "1.11.0"
conscrypt = "2.5.2"
orgjson = "20240303"

[libraries]
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "coroutines" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
jackson-module-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson" }
nicehttp = { group = "com.github.Blatzar", name = "NiceHttp", version.ref = "nicehttp" }
rhino = { group = "org.mozilla", name = "rhino", version.ref = "rhino" }
ktor-http = { group = "io.ktor", name = "ktor-http", version.ref = "ktor" }
ksoup = { group = "com.fleeksoft.ksoup", name = "ksoup", version.ref = "ksoup" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "datetime" }
atomicfu = { group = "org.jetbrains.kotlinx", name = "atomicfu", version.ref = "atomicfu" }
newpipeextractor = { group = "com.github.teamnewpipe", name = "NewPipeExtractor", version.ref = "newpipeextractor" }
cryptography-core = { group = "dev.whyoleg.cryptography", name = "cryptography-core", version.ref = "cryptography" }
cryptography-provider-optimal = { group = "dev.whyoleg.cryptography", name = "cryptography-provider-optimal", version.ref = "cryptography" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serializationJson" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
conscrypt-openjdk = { group = "org.conscrypt", name = "conscrypt-openjdk-uber", version.ref = "conscrypt" }
orgjson = { group = "org.json", name = "json", version.ref = "orgjson" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
javafx = { id = "org.openjfx.javafxplugin", version = "0.1.0" }
